<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxzxvns\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxzxvns/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNxzxvns.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNxzxvns\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNxzxvns\appProdProjectContainer([
    'container.build_hash' => 'Nxzxvns',
    'container.build_id' => '9ffa34c6',
    'container.build_time' => 1646508467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxzxvns');
